

try {
  console.log(naoExito);  
} catch (err){
    console.log("naoExisto n√£o existe")
    console.log(err);
}